### ISSUE TITLE
Image not defined

### ISSUE THREAD

**Issue by kasperaamodt** [kimcoder/react-simple-image-slider#29]
Hi, installed this component today, and whenever i try to use it, I get a ReferenceError: 

ReferenceError: Image is not defined
    at eval (webpack-internal:///./node_modules/react-simple-image-slider/dist/index.js:4:2477)
    at Array.map (<anonymous>)
    at eval (webpack-internal:///./node_modules/react-simple-image-slider/dist/index.js:4:2462)
    at eval (webpack-internal:///./node_modules/react-simple-image-slider/dist/index.js:4:2820)
    at Module../node_modules/react-simple-image-slider/dist/index.js

**Comment by kimcoder** [comment]
Hi, @kasperaamodt Can you try to install v2.0.2?

**Comment by kasperaamodt** [comment]
I tried it again today, still Image not defined.

**Comment by camilojm27** [comment]
I got the same with Next.JS 

`ReferenceError: Image is not defined
    at node_modules/react-simple-image-slider/dist/ImageSlider.js:59:5
    at Array.map (<anonymous>)
    at node_modules/react-simple-image-slider/dist/ImageSlider.js:58:51
    at Object.<anonymous> (/home/camilo/Projects/celina/frontend/node_modules/react-simple-image-slider/dist/ImageSlider.js:85:2)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18) {
  type: 'ReferenceError'
}
`

**Comment by kimcoder** [comment]
@kasperaamodt, @camilojm27 
Hi Guys, 
This issue are resolved in v2.1.1.

Thanks you.
